apiVersion: apps/v1
kind: Deployment
metadata:
  name: loidv-deployment
  namespace: python-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loidv
  template:
    metadata:
      labels:
        app: loidv
    spec:
      containers:
        - name: loidv
          image: loidv01071999/devopstest:latest
          imagePullPolicy: "Always"
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_DATABASE
              value: your_database_name
            - name: DB_USERNAME
              value: your_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password

---
apiVersion: v1
kind: Service
metadata:
  name: loidv-service
  namespace: python-demo
spec:
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: loidv
---

